#!/usr/bin/env bash
# File:        synctasks.sh
# Author:      Tristan Andrus
# Description: Syncs personal tasks from taskwarrior
################################################################################

set -o errexit   # Abort on nonzero exitstatus
set -o nounset   # Abort on unbound variable
set -o pipefail  # Don't hide errors within pipes

trap "echo 'An error occurred! Quitting mid-script!'" ERR

# Colors for more visual statuses
_RED_TEXT='\033[31m'
_GREEN_TEXT='\033[32m'
_YELLOW_TEXT='\033[33m'
_CLEAR_TEXT='\033[0m'

function echo_warning() { echo -e "${_YELLOW_TEXT}$*${_CLEAR_TEXT}" ;}
function echo_error()   { echo -e "${_RED_TEXT}$*${_CLEAR_TEXT}"    ;}
function echo_success() { echo -e "${_GREEN_TEXT}$*${_CLEAR_TEXT}"  ;}
# Uncomment to debug
# set -x

################################################################################

# This got much simpler with TaskChampion v3
task sync
